name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true
        env:
          HD_TDX_HOST: ${{ secrets.TDX_HOST }}
          HD_TDX_API_ID: ${{ secrets.TDX_API_ID }}
          HD_TDX_API_KEY: ${{ secrets.TDX_API_KEY }}
